Make test pass again
digi-serve/appbuilder_class_core pull request #219
Opened 2024-02-29 04:46 UTC by wongpratan

## Release Notes

- Trying to to pass e2e testings

2024-02-29 09:49 UTC, nh758 approved these changes
Looks ok to me

2024-02-29 09:49 UTC, nh758 commented on .github/workflows/merging-rules.yml
> +    branches: [periodOfTime]
will need to update before merging to v2

2024-02-29 18:43 UTC, Hiro-Nakamura requested changes
This works if the Cursor as `Added` new data.  

But you aren't checking to see if the Cursor has `Removed` any items that you currently have.

2024-02-29 18:43 UTC, Hiro-Nakamura commented on ABDataCollectionCore.js
> +               const newItem = this.AB.cloneDeep(item);
To answer your question: Yes, you need to perform a .find to get the fully populated data for use in your DataCollection.

You could look at reusing the `this.datasource.model().staleRefresh()` as that does some buffering to only make 1 call even if you are asking for 10 new items.

2024-03-01 04:06 UTC, wongpratan commented
> This works if the Cursor as `Added` new data.
> 
> But you aren't checking to see if the Cursor has `Removed` any items that you currently have.

I don't sure what do you mean `unrelate` value or `remove` the cursor.
I checked it.  Both of them should work already.

When user `unrelate` value, then data should be filtered by [this](https://github.com/digi-serve/appbuilder_class_core/pull/219/files#diff-23eae8127a35e681261fee3393f168256b08a4b3807123f4666060de7359c2bcR1317).
or When the cursor will be removed, then the list should be clear.

2024-03-01 04:21 UTC, wongpratan commented on ABDataCollectionCore.js
> +               const newItem = this.AB.cloneDeep(item);
@Hiro-Nakamura @nh758 
Would it be better if only DC that set `.loadAll` = **true** load immediately ?

but DC that has load partial data (paging), then there is display a warning message to user to reload data.
https://github.com/digi-serve/appbuilder_class_core/pull/219/files#diff-23eae8127a35e681261fee3393f168256b08a4b3807123f4666060de7359c2bcR2645

It would be prevent clients flood request to the server even if user might not need to see data in that time.

2024-03-01 07:47 UTC, guyyoo approved these changes
LGTM!

2024-03-04 04:16 UTC, merged