Add field types
digi-serve/appbuilder_class_core pull request #59
Opened 2022-02-25 08:00 UTC by guyyoo

2022-03-01 14:09 UTC, Hiro-Nakamura requested changes
Some Comments:

Each of our `ABFieldXXXCore` files need some reworking.
- The `ABFieldXXXDefaults` values all need to have their values commented.  Take a look at the `ABFieldStringCore` and `ABFieldNumberCore` examples.  Keep the values in the same order with the same documentation in each of the new `ABFieldXXX` fields you move over to the ABDesigner
- Notice how not every `ABFieldXXXCore` has all the values in their `ABFieldStringDefaults` settings. Take a look at `ABFieldAutoIndexCore` and you'll see that it only defines about 4 of the possible fields.  Go through each of these `ABFieldXXXCore` definitions and fill out all the values.
- in the `ABFieldXXXDefaults`  both the `description`  and `menuName` values should now simply be the `L(key)` that gets displayed.  So remove the current `L()` for those settings and just put the `key`
- anytime you see the old `"Some String #key#".replace("#key#", value);`  replace them with the more modern ``` `Some String ${value}` ``` form.

2022-03-01 14:09 UTC, Hiro-Nakamura commented on dataFields/ABFieldTextFormulaCore.js
> +      localeCode: abFactory.Config._config.user.languageCode,
this should be `abFactory.Account.language()`

Better yet, rename `abFactory`  to `AB` to maintain consistency with the rest of our code.

2022-03-01 14:09 UTC, Hiro-Nakamura commented on dataFields/ABFieldTextFormulaCore.js
> +      localeCode: abFactory.Config._config.user.languageCode,
`AB.Account.language()`

2022-03-01 14:09 UTC, Hiro-Nakamura commented on dataFields/ABFieldTextFormulaCore.js
> +      localeCode: abFactory.Config._config.user.languageCode,
just to point out ...

Anytime you reference a private inner value of an object, that is a `no-no`.  For example: `Config._config`  the `_` prefix is supposed to warn you that this is private.  You should be using an exposed method to access any of that data.

2022-03-02 04:25 UTC, guyyoo commented
@Hiro-Nakamura Thank you so much. I will fix it soon.

2022-03-07 03:26 UTC, guyyoo commented on dataFields/ABFieldConnectCore.js
> -            (String(names[1]).replace(/[^a-z0-9\.]/gi, "") + "__relation")
For this, Prettier tell me the `\` is "Unnecessary escape character: [.eslintno-useless-escape". I am not sure I should ignore?

2022-03-07 03:26 UTC, guyyoo commented on dataFields/ABFieldEmailCore.js
> -         var Reg = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
For this, Prettier tell me the `\` is "Unnecessary escape character: [.eslintno-useless-escape". I am not sure I should ignore?

2022-03-09 07:05 UTC, Hiro-Nakamura requested changes
OK, just a couple more things to fix.

2022-03-09 10:37 UTC, guyyoo commented on dataFields/ABFieldEmailCore.js
> +   supportUnique: false,
Ok, I will bring this up 👍

2022-03-10 03:19 UTC, guyyoo commented on dataFields/ABFieldEmailCore.js
> +   supportUnique: false,
I have talked with the team. I think it should support unique.

2022-03-10 05:12 UTC, Hiro-Nakamura approved these changes
Looking good!

2022-03-10 08:00 UTC, merged